/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'brent.gardner' at '10/31/16 4:51 PM' with Gradle 3.1
 *
 * @author brent.gardner, @date 10/31/16 4:51 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
